version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scoreboard
    ports:
      - 3307:3306
    networks:
      - springNetwork

  appl:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_PORT=3307
      - MYSQL_HOST=172.17.0.1
      - MYSQL_DATABASE=scoreboard
    networks:
      - springNetwork
    depends_on:
      - mysqldb
    restart: always
networks:
    springNetwork: