version: "3.7"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scoreboard
    ports:
      - 3307:3306
    extra_hosts:
          - "host.docker.internal:host-gateway"
    networks:
      - springNetwork


  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_PORT=3307
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=scoreboard
    networks:
      - springNetwork
    depends_on:
      - mysqldb
    restart: always
networks:
    springNetwork: